default_language_version:
    python: python3
default_stages: [commit, push]
fail_fast: false
minimum_pre_commit_version: 1.15.0
exclude: (.ini|.md)$
repos:
  - repo: local
    hooks:
      - id: lint
        name: fmt-local
        description: 'Format Python code by running "make fmt"'
        language: system
        types: [python]
        entry: make fmt lint
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: flake8
        entry: pflake8
        additional_dependencies: [ pyproject-flake8 ]
